version: '3.6'
services:

  app:
    build: ./app
    container_name: mef
    expose:
      - 80
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
