version: '3.6'
services:

  app:
    build: ./app
    container_name: mef
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8085:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/code:/var/www/html"
      - "./nginx/certs/nginx.crt:/etc/nginx/ssl/nginx.crt"
      - "./nginx/certs/nginx.key:/etc/nginx/ssl/nginx.key"
    depends_on:
      - app
